{% set version = "2.4.0" %}

package:
  name: tmate
  version: {{ version }}

source:
  url: https://github.com/tmate-io/tmate/archive/{{ version }}.tar.gz
  sha256: 62b61eb12ab394012c861f6b48ba0bc04ac8765abca13bdde5a4d9105cb16138

build:
  number: 6
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config
    - make

  host:
    - libevent
    - ncurses
    - msgpack-c
    - libssh
    # conda claims that we are overlinking to krb5... not sure why
    - krb5
    # Something is leaking an openssl symbol, not sure why
    # https://github.com/conda-forge/tmate-feedstock/issues/10
    - openssl

  run:
    # TODO: add run exports for msgpack-c
    - msgpack-c

test:
  commands:
    - tmate -V
    # Check that no server is running.
    - $(tmate info || true) 2> >(grep "no server running on")

about:
  home: https://tmate.io/
  dev_url: https://github.com/tmate-io/tmate
  license: ISC
  license_file: COPYING
  summary: Instant Terminal Sharing.

extra:
  recipe-maintainers:
    - hmaarrfk
    - matthiasdiener
